namespace Fluxor.UnitTests.DependencyInjectionTests.ReducerDiscoveryTests.DiscoverReducersWithActionInAttributeTests.TypesThatShouldOnlyBeScannedExplicitly;

public class DoNotScanThisNamespace : Middleware
{
}
