namespace Fluxor.UnitTests.DependencyInjectionTests.FeatureDiscoveryTests.DiscoverFeatureStateAttributeTests.SupportFiles;

[FeatureState]
public class StateWithParameterlessFeatureStateAttribute
{
}
